
version: '3.4'
services:
  confluence:
    image: cptactionhank/atlassian-confluence:latest
    container_name: confluence
    ports:
      - "8090:8090"
      - "8091:8091"
    restart: always
    depends_on:
      - db
    volumes:
      - ./logs:/opt/atlassian/confluence/logs
      - ./confluence:/var/atlassian/confluence
  db:
    image: postgres:9.4
    container_name: confluence-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=456123
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
