version: "3.4"
services:
    web:
      image: 'gitlab/gitlab-ce:latest'
      container_name: gitlab
      restart: always
      hostname: '192.168.124.25'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.124.25:8929'
          gitlab_rails['gitlab_shell_ssh_port'] = 2224
         
      ports:
        - '8929:8929'
        - '2224:22'
      volumes:
        - './config:/etc/gitlab'
        - './logs:/var/log/gitlab'
        - './data:/var/opt/gitlab'
     