version: '3.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  
      - TZ=Asia/Shanghai   
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/lyy/docker_shell/elasticsearch/data01:/usr/share/elasticsearch/data
      - /home/lyy/docker_shell/elasticsearch/logs01:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    
    networks:
      default:
        ipv4_address: 172.23.0.92
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Shanghai  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/lyy/docker_shell/elasticsearch/data02:/usr/share/elasticsearch/data
      - /home/lyy/docker_shell/elasticsearch/logs02:/usr/share/elasticsearch/logs
    ports:
      - 9201:9200
    networks:
      default:
        ipv4_address: 172.23.0.93
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
      - TZ=Asia/Shanghai
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/lyy/docker_shell/elasticsearch/data03:/usr/share/elasticsearch/data
      - /home/lyy/docker_shell/elasticsearch/logs03:/usr/share/elasticsearch/logs
    ports:
      - 9202:9200
    networks:
      default:
        ipv4_address: 172.23.0.94
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=["http://192.168.3.13:9200","http://192.168.3.13:9201","http://192.168.3.13:9202"]
      - TZ=Asia/Shanghai
    volumes:
    - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es01
      - es02
      - es03
    ports:
      - 5601:5601 
    networks:
      default:
        ipv4_address: 172.23.0.56
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash01
    hostname: logstash
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config
    depends_on:
      - es01
      - es02
      - es03
    ports:
        - "5044:5044"
    networks:
      default:
        ipv4_address: 172.23.0.44
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  default:
    external:
      name: zookeeper_network
