version: "3.3"

services:

  hbase-master:
    image: bde2020/hbase-master:1.0.0-hbase1.2.6
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 zoo1:2181"
    ports:
      - 16010:16010
      - 16000:16000     # 新添加
    networks: 
      - custom_net

  hbase-region:
    image: bde2020/hbase-regionserver:1.0.0-hbase1.2.6
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - ./hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 zoo1:2181 hbase-master:16010"
    ports:
      - 16030:16030
      - 16020:16020   # 新添加
    networks: 
      - custom_net

networks:
  custom_net:
    external:
      name: ants_platform_net