version: '3.1'
services: 
    db:
      # images 8.x
      image: mysql
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: 456123
        MYSQL_ROOT_HOST: '%'
      command: 
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --explicit_defaults_for_timestamp=true
        --lower_case_table_names=1
        --default-time-zone=+8:00
        --skip-name-resolve
        --wait_timeout=28800
      ports: 
        - 3309:3306
      volumes: 
        - ./data:/var/lib/mysql